services:
  dev-pc:
    image: 127.0.0.1:5000/debian-podman-ssh:12.1
    privileged: true
    ports:
      - 2224:22/tcp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/dev:/home/debian:z
      - ./init:/app/init:z,ro
    depends_on:
      - oracle-pc
    networks:
      fake-cloud-net:
      deployment-net:

  uat-pc:
    image: 127.0.0.1:5000/debian-podman-ssh:12.1
    privileged: true
    ports:
      - 2223:22/tcp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/uat:/home/debian:z
      - ./init:/app/init:z,ro
    depends_on:
      - oracle-pc
    networks:
      fake-cloud-net:
      deployment-net:

  master-pc:
    image: 127.0.0.1:5000/debian-podman-ssh:12.1
    privileged: true
    ports:
      - 2222:22/tcp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./home/master:/home/debian:z
      - ./init:/app/init:z,ro
    depends_on:
      - oracle-pc
    networks:
      fake-cloud-net:
      deployment-net:

  oracle-pc:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 2521:1521
    restart: unless-stopped
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracle-pc-data:/opt/oracle/oradata:z,rw
    networks:
      fake-cloud-net:

  sonarqube-server:
    image: docker.io/sonarqube:10.1.0-community
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonarqube-db
    networks:
      devops-net:

  sonarqube-db:
    image: docker.io/postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data:z,rw
    networks:
      devops-net:

  jenkins:
    image: 127.0.0.1:5000/jenkins-docker:2.401.3-lts-jdk17
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      devops-net:
      deployment-net:

  local-registry:
    image: docker.io/registry:2
    expose:
      - 5000
    networks:
      deployment-net:

volumes:
  oracle-pc-data:
  sonarqube-db-data:
  jenkins-data:

networks:
  deployment-net:
  devops-net:
  fake-cloud-net:
